### ISSUE TITLE
currentMovieTitle global variable not updating before showMovieTrailer() is run

### ISSUE THREAD

**Issue by atakori** [atakori/Now-Playing-App#1]
The trailers are not updating appropriately (They are always one search result behind). If you use the genre 'horror', the movie generator comes up with the movie IT. However, the trailer it included was completely random (Unfriended). Then I randomly searched for a second movie, the generator came up with the first movie's trailer (IT) along with a new movie title/information. Every time I generate a new movie, the trailer is always the one from the previous search result. 

I think the problem has to do with my global variable of currentMovieTitle not updating before the youtube function is called to grab the movie trailer based off the current movie title. Does the global variable not update according to the order that you set in your code?

In the function handleRandomMovieButton(), displayMovieInformation() is where the global variable of currentMovieTitle is updated. This seems to also be messing with my other features (adding the movie name to an array so that if the user has already seen it, the same movie will not pop up again). Is there a way to get around this?

**Comment by krokhale** [comment]
- Just cloned the code and looked through it.

- There is definetly some asynchronous activity going on. I also noticed there are some endless loops being triggered.

- You are very close but we will need to refactor the code so that functions execute in order.

- Right now, they seem to be called in parallel and are overwriting global variables randomly.

- Let's catch up and pair program through this.

- By the way good job with splitting apart functions for the various tasks they perform.

**Comment by krokhale** [comment]
Resolved during mentoring session.
